#!/usr/bin/env python3
"""
pyrobot-cli — plugin scaffolding for PyRobot Studio.

    python -m sdk.cli create-plugin my_filter --category Processing \\
        --input in:image --output out:image

Generates a ready-to-run plugin file under plugins/user/<name>.py with:
  - a correctly-shaped PluginManifest (id, category, ports, one example param)
  - a Node subclass with on_message stubbed in (for a node with inputs) or
    on_start/on_stop stubbed in (for a source node with no inputs)
  - enough working code that it's immediately discoverable by the backend's
    plugin registry and shows up in the Studio palette without edits —
    the intent is "generate something that runs", not just a doc comment.

This is intentionally a plain argparse script with a template string, not
a separate package — so it has zero extra dependencies beyond the SDK
itself, and works the moment you clone the repo.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

VALID_PORT_TYPES = {"image", "pointcloud", "pose", "imu", "string", "number", "bool", "json", "any"}

SOURCE_TEMPLATE = '''"""
{class_name} — generated by pyrobot-cli create-plugin.

A source node: no inputs, produces output on its own (e.g. on a timer).
Fill in _run() with your actual capture/generation logic.
"""

import threading
import time

from sdk.pyrobot_plugin import Node, PluginManifest, PortSpec, PortDataType, ParamSpec


class {class_name}(Node):
    manifest = PluginManifest(
        id="{plugin_id}",
        name="{display_name}",
        category="{category}",
        description="TODO: describe what this node does.",
        outputs=[
{output_ports}
        ],
        params=[
            ParamSpec(name="rate_hz", kind="number", default=10, min=1, max=200),
        ],
    )

    def on_start(self) -> None:
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def on_stop(self) -> None:
        self._stop.set()

    def _run(self) -> None:
        rate_hz = self.get_param("rate_hz", 10)
        period = 1.0 / rate_hz
        while not self._stop.is_set():
            # TODO: replace with real data
{emit_calls}
            self._stop.wait(period)
'''

PROCESSING_TEMPLATE = '''"""
{class_name} — generated by pyrobot-cli create-plugin.

A processing node: reacts to messages on its input port(s) and (optionally)
emits on its output port(s). Fill in on_message() with your actual logic.
"""

from sdk.pyrobot_plugin import Node, PluginManifest, PortSpec, PortDataType, ParamSpec


class {class_name}(Node):
    manifest = PluginManifest(
        id="{plugin_id}",
        name="{display_name}",
        category="{category}",
        description="TODO: describe what this node does.",
        inputs=[
{input_ports}
        ],
        outputs=[
{output_ports}
        ],
        params=[],
    )

    def on_message(self, port: str, message) -> None:
        # TODO: replace with real processing logic
{emit_calls}
'''


def to_class_name(slug: str) -> str:
    parts = re.split(r"[_\-\s]+", slug.strip())
    return "".join(p.capitalize() for p in parts if p) + "Node"


def parse_port_spec(spec: str) -> tuple[str, str]:
    if ":" not in spec:
        sys.exit(f"Port spec '{spec}' must be in the form name:type (e.g. frame:image)")
    name, _, dtype = spec.partition(":")
    if dtype not in VALID_PORT_TYPES:
        sys.exit(f"Unknown port type '{dtype}' in '{spec}'. Valid types: {sorted(VALID_PORT_TYPES)}")
    return name, dtype


def render_ports(ports: list[tuple[str, str]]) -> str:
    if not ports:
        return ""
    lines = [f'            PortSpec("{name}", PortDataType.{dtype.upper()}),' for name, dtype in ports]
    return "\n".join(lines)


def render_emit_calls(outputs: list[tuple[str, str]]) -> str:
    if not outputs:
        return "            pass"
    lines = []
    for name, _ in outputs:
        lines.append(f'            self.emit("{name}", {{}})  # TODO: populate real payload')
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(prog="pyrobot-cli", description="PyRobot Studio plugin scaffolding")
    sub = parser.add_subparsers(dest="command", required=True)

    create = sub.add_parser("create-plugin", help="Generate a new plugin file")
    create.add_argument("name", help="Plugin slug, e.g. 'my_filter' (used for the id, filename, and class name)")
    create.add_argument("--category", default="Processing", help="Palette category (default: Processing)")
    create.add_argument("--author", default="", help="Author id prefix for the plugin id (default: 'user')")
    create.add_argument("--input", action="append", default=[], metavar="name:type", help="Input port, repeatable, e.g. --input frame:image")
    create.add_argument("--output", action="append", default=[], metavar="name:type", help="Output port, repeatable, e.g. --output result:json")
    create.add_argument("--out-dir", default="plugins/user", help="Directory to write into (default: plugins/user)")
    create.add_argument("--force", action="store_true", help="Overwrite if the file already exists")

    args = parser.parse_args()

    if args.command == "create-plugin":
        inputs = [parse_port_spec(s) for s in args.input]
        outputs = [parse_port_spec(s) for s in args.output]

        slug = re.sub(r"[^a-z0-9_]+", "_", args.name.strip().lower())
        class_name = to_class_name(slug)
        author = args.author or "user"
        plugin_id = f"{author}.{slug}"
        display_name = " ".join(p.capitalize() for p in slug.split("_"))

        is_source = len(inputs) == 0
        template = SOURCE_TEMPLATE if is_source else PROCESSING_TEMPLATE

        content = template.format(
            class_name=class_name,
            plugin_id=plugin_id,
            display_name=display_name,
            category=args.category,
            input_ports=render_ports(inputs),
            output_ports=render_ports(outputs),
            emit_calls=render_emit_calls(outputs),
        )

        out_dir = Path(args.out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / f"{slug}.py"
        if out_path.exists() and not args.force:
            sys.exit(f"{out_path} already exists — pass --force to overwrite")
        out_path.write_text(content, encoding="utf-8")
        print(f"Created {out_path}")
        print(f"  plugin id: {plugin_id}")
        print(f"  category:  {args.category}")
        print(f"  inputs:    {inputs or '(none — this is a source node)'}")
        print(f"  outputs:   {outputs or '(none)'}")
        print()
        print("plugins/user is discovered automatically. For other folders, use the runtime's --plugin-dir option.")


if __name__ == "__main__":
    main()
